name = "cwtest4"
main = "src/index.ts"
compatibility_date = "2024-02-20"

# D1データベースの設定
[[d1_databases]]
binding = "DB"
database_name = "doctor_matching"
database_id = "53cf0f3d-0839-4df7-9723-4c63ac99ee10"

# 静的ファイルの設定
[site]
bucket = "./"

# 環境変数
[vars]
JWT_SECRET = "50ed1ca190a3a4188a611a33187de9ca9845d1cabfd5e758d5c2561904d20669f1f32c8f69987051c009f769900b0a7709a3a27da207b1d91eefa1c5bec2fc91"

# ビルド設定
[build]
command = "npm run build"
upload.format = "directory"

# 本番環境の設定
[env.production]
name = "cwtest4"
route = "cwtest4.pages.dev"
workers_dev = false 